/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const Time = IDL.Int;
export const ArticleCategory = IDL.Variant({
  'rumors' : IDL.Null,
  'news' : IDL.Null,
  'results' : IDL.Null,
  'events' : IDL.Null,
});
export const Article = IDL.Record({
  'id' : IDL.Nat32,
  'content' : IDL.Text,
  'publishDate' : Time,
  'summary' : IDL.Text,
  'imageUrl' : IDL.Text,
  'promotion' : IDL.Text,
  'category' : ArticleCategory,
});
export const UserProfile = IDL.Record({
  'savedArticles' : IDL.Vec(IDL.Nat32),
  'readingHistory' : IDL.Vec(IDL.Nat32),
  'favoritePromotions' : IDL.Vec(IDL.Text),
  'darkMode' : IDL.Bool,
  'rumorAlerts' : IDL.Bool,
  'breakingNewsAlerts' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'deleteArticle' : IDL.Func([IDL.Nat32], [], []),
  'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getArticleById' : IDL.Func([IDL.Nat32], [IDL.Opt(Article)], ['query']),
  'getArticlePreviewImage' : IDL.Func([IDL.Nat32], [IDL.Text], ['query']),
  'getArticlesByCategory' : IDL.Func(
      [ArticleCategory],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getArticlesByPromotion' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getArticlesByPromotionAndCategory' : IDL.Func(
      [IDL.Text, ArticleCategory],
      [IDL.Vec(Article)],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getProfile' : IDL.Func([], [UserProfile], ['query']),
  'getReadingHistory' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getSavedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveProfile' : IDL.Func([UserProfile], [], []),
  'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
  'uploadArticle' : IDL.Func([Article], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const Time = IDL.Int;
  const ArticleCategory = IDL.Variant({
    'rumors' : IDL.Null,
    'news' : IDL.Null,
    'results' : IDL.Null,
    'events' : IDL.Null,
  });
  const Article = IDL.Record({
    'id' : IDL.Nat32,
    'content' : IDL.Text,
    'publishDate' : Time,
    'summary' : IDL.Text,
    'imageUrl' : IDL.Text,
    'promotion' : IDL.Text,
    'category' : ArticleCategory,
  });
  const UserProfile = IDL.Record({
    'savedArticles' : IDL.Vec(IDL.Nat32),
    'readingHistory' : IDL.Vec(IDL.Nat32),
    'favoritePromotions' : IDL.Vec(IDL.Text),
    'darkMode' : IDL.Bool,
    'rumorAlerts' : IDL.Bool,
    'breakingNewsAlerts' : IDL.Bool,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'deleteArticle' : IDL.Func([IDL.Nat32], [], []),
    'getAllArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getArticleById' : IDL.Func([IDL.Nat32], [IDL.Opt(Article)], ['query']),
    'getArticlePreviewImage' : IDL.Func([IDL.Nat32], [IDL.Text], ['query']),
    'getArticlesByCategory' : IDL.Func(
        [ArticleCategory],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getArticlesByPromotion' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getArticlesByPromotionAndCategory' : IDL.Func(
        [IDL.Text, ArticleCategory],
        [IDL.Vec(Article)],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getProfile' : IDL.Func([], [UserProfile], ['query']),
    'getReadingHistory' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getSavedArticles' : IDL.Func([], [IDL.Vec(Article)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveProfile' : IDL.Func([UserProfile], [], []),
    'searchArticles' : IDL.Func([IDL.Text], [IDL.Vec(Article)], ['query']),
    'uploadArticle' : IDL.Func([Article], [], []),
  });
};

export const init = ({ IDL }) => { return []; };