/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Article {
  'id' : number,
  'content' : string,
  'publishDate' : Time,
  'summary' : string,
  'imageUrl' : string,
  'promotion' : string,
  'category' : ArticleCategory,
}
export type ArticleCategory = { 'rumors' : null } |
  { 'news' : null } |
  { 'results' : null } |
  { 'events' : null };
export type Time = bigint;
export interface UserProfile {
  'savedArticles' : Uint32Array,
  'readingHistory' : Uint32Array,
  'favoritePromotions' : Array<string>,
  'darkMode' : boolean,
  'rumorAlerts' : boolean,
  'breakingNewsAlerts' : boolean,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'deleteArticle' : ActorMethod<[number], undefined>,
  'getAllArticles' : ActorMethod<[], Array<Article>>,
  'getArticleById' : ActorMethod<[number], [] | [Article]>,
  'getArticlePreviewImage' : ActorMethod<[number], string>,
  'getArticlesByCategory' : ActorMethod<[ArticleCategory], Array<Article>>,
  'getArticlesByPromotion' : ActorMethod<[string], Array<Article>>,
  'getArticlesByPromotionAndCategory' : ActorMethod<
    [string, ArticleCategory],
    Array<Article>
  >,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getProfile' : ActorMethod<[], UserProfile>,
  'getReadingHistory' : ActorMethod<[], Array<Article>>,
  'getSavedArticles' : ActorMethod<[], Array<Article>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveProfile' : ActorMethod<[UserProfile], undefined>,
  'searchArticles' : ActorMethod<[string], Array<Article>>,
  'uploadArticle' : ActorMethod<[Article], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];